name: Update localizations (JSON)
on:
  push:
    branches:
      - main

jobs:
  update-localizations:
    name: Update Frontmatter Dates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Cache .aicache
        uses: actions/cache@v3
        with:
          path: .aicache
          key: openai-cache

      - run: npm ci

      - name: npm run localize
        env:
          VITE_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run localize

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: public/locales/*.json
          commit-message: Update localizization JSON files
          title: Update localizization JSON files
          body: Update localizization JSON files
          branch: update-localizations
          delete-branch: true
          labels: github-action
