# This is a github action to create a Pull request
# it won't run if there are other PRs from teh action still open

name: Update Frontmatter Dates
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-frontmatter-dates:
    name: Update Frontmatter Dates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update frontmatter dates using .github/scripts/update-frontmatter-dates.sh
        run: .github/scripts/update-frontmatter-dates.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: src/content/*.md
          commit-message: Update frontmatter dates
          title: Update datePuiblish and dateUpdated
          body: Update all .md files to have the same datePublished and dateUpdated as the git log
          branch: update-frontmatter-dates
          delete-branch: true
          labels: github-action
